name: CI

on:
  pull_request:

env:
  LANG: ja_JP.UTF-8
jobs:
  ci:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6

      - name: Install locale
        run: |
          sudo locale-gen "${LANG}"
          sudo update-locale

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24.15.0

      - name: Cache dependencies
        uses: actions/cache@v5
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm ci
      - run: npm run test-once
